spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.product.domain
dubbo:
  scan:
    basePackages: com.product.service.impl
  application:
    id: product
    name: product
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  registry:
    id: my-product
    address: 127.0.0.1:2181
    protocol: zookeeper
    client: curator
    timeout: 3000
product:
  service:
    version: 1.0.0
#重试次数
curator:
  retryCount: 5
  #重试间隔时间
  elapsedTimeMs: 5000
  # zookeeper 地址
  connectString: 127.0.0.1:2181
  # session超时时间
  sessionTimeoutMs: 60000
  # 连接超时时间
  connectionTimeoutMs: 5000